version: '3.8'

services:
  backend:
    build: ../../dockerfiles/example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - db
      - redis
    ports:
      - 8080:8080

  frontend:
    build: ../../dockerfiles/example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
  
  redis:
    image: redis:7.2.4
  
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - type: bind
        source: ./static
        target: /var/lib/postgresql/data
  
  proxy:
    image: nginx:alpine3.18
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
