version: '3.8'

services:
  backend:
    build: ../../dockerfiles/example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on:
      - db

  frontend:
    build: ../../dockerfiles/example-frontend
    ports:
      - 5001:5001
  
  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
  
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - type: bind
        source: ./static
        target: /var/lib/postgresql/data
  
  proxy:
    image: nginx:alpine3.18
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
